services:
  postgres:
    image: postgres:16
    container_name: selfinterior-postgres
    environment:
      POSTGRES_DB: selfinterior
      POSTGRES_USER: selfinterior
      POSTGRES_PASSWORD: selfinterior
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: selfinterior-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
