package com.selfinterior.api.common.api;

public enum ErrorCode {
  BAD_REQUEST,
  PROJECT_NOT_FOUND,
  PROPERTY_NOT_FOUND,
  FLOOR_PLAN_NOT_FOUND,
  PROCESS_PLAN_NOT_FOUND,
  PROCESS_PLAN_GENERATION_BLOCKED,
  PROCESS_TASK_NOT_FOUND,
  VISUAL_QUESTION_NOT_FOUND,
  EXPERT_NOT_FOUND,
  EXPERT_CATEGORY_NOT_FOUND,
  STYLE_PRESET_NOT_FOUND,
  STYLE_IMAGE_NOT_FOUND,
  INTERNAL_ERROR
}
