package com.selfinterior.api.common.api;

public enum ErrorCode {
  BAD_REQUEST,
  PROJECT_NOT_FOUND,
  PROPERTY_NOT_FOUND,
  FLOOR_PLAN_NOT_FOUND,
  PROCESS_PLAN_NOT_FOUND,
  PROCESS_PLAN_GENERATION_BLOCKED,
  PROCESS_TASK_NOT_FOUND,
  INTERNAL_ERROR
}
